#!/usr/local/bin/ruby

# This goes instead of dialog(1), it will
# just return the default options selection
#
# Ex: make config DIALOG=default-dialog

box = ARGV[0]
exit(-1) unless box == "--checklist"

text, height, width, list_height = ARGV[1, 4]

i = 5
while i < ARGV.count do
  tag, item, status = ARGV[i, 3]
  if status == "on"
    $stderr.puts tag
  end
  i += 3
end

# "OK"
exit(0)
