#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 Richard Hughes <richard@hughsie.com>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

obj = bld.create_obj('cc', 'program')
obj.source='pk-console.c'
obj.includes='. ../libpackagekit'
obj.uselib='GLIB GOBJECT DBUS_GLIB POLKIT_DBUS GTHREAD'
obj.uselib_local='libpackagekit'
obj.target='pkcon'

obj = bld.create_obj('cc', 'program')
obj.source='pk-monitor.c'
obj.includes='. ../libpackagekit'
obj.uselib='GLIB GOBJECT DBUS_GLIB POLKIT_DBUS GTHREAD'
obj.uselib_local='libpackagekit'
obj.target='pkmon'
