def build(bld):
	obj = bld.create_obj('cc', 'plugin')
	obj.target = 'pk_backend_yum'
	obj.source = 'pk-backend-yum.c'
	obj.uselib = 'YUM'
	obj.uselib_local = 'libpackagekit'
	obj.includes = '../../src ../../libpackagekit'
	obj.install_var = 'LIBDIR'
	obj.install_subdir = 'packagekit-backend'

def configure(conf):
	if not conf.find_program('yum'):
		return False

	# Additional checks required
	return False

def set_options(opt):
	pass
