#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 Richard Hughes <richard@hughsie.com>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

import Common

#install the data files
Common.install_files('PREFIX', os.path.join('etc', 'yum', 'pluginconf.d'), 'refresh-packagekit.conf')
Common.install_files('PREFIX', os.path.join('usr', 'lib', 'yum-plugins'), 'refresh-packagekit.py')

