task:
  name: "Build & Test (freebsd)"
  freebsd_instance:
    matrix:
      - image_family: freebsd-14-2
  deps_script:
    - mkdir -p /usr/local/etc/pkg/repos/
    - sed 's|/quarterly|/latest|' /etc/pkg/FreeBSD.conf > /usr/local/etc/pkg/repos/FreeBSD.conf
    - env ASSUME_ALWAYS_YES=yes pkg update -f
    - env ASSUME_ALWAYS_YES=yes pkg install -y docbook-xsl vala libxslt fontconfig polkit consolekit2
        desktop-file-utils gettext meson ninja python3 glib gtk3 pkgconf sqlite3 gobject-introspection
        dbus bash
  build_script:
    - meson --auto-features=enabled -Db_colorout=never --buildtype debug -Dlocal_checkout=true -Dlocalstatedir=/var
        -Dsystemd=false -Doffline_update=false  -Dbash_completion=false -Dbash_command_not_found=false
        -Dgstreamer_plugin=false -Dpackaging_backend=freebsd _build
    - cd _build
    - ninja all
  test_script:
   - cd _build
   - service dbus onestart
   - ninja test
