#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005-2008

"""
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

3. The name of the author may not be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
"""

import os, sys
if sys.hexversion<0x203000f: raise "Waf needs Python >= 2.3"

if 'PSYCOWAF' in os.environ:
	try:import psyco;psyco.full()
	except:pass

VERSION="1.3.2"
REVISION="x"
INSTALL="x"
cwd=os.getcwd()
j=os.path.join

def decode(s):
	out=[]
	a=out.append
	d=divmod
	p1,p2=d(len(s),5)
	stop=5*p1
	p3,p4=s[0:stop],s[stop:]

	def u(v, o):
		return ord(v[o])-33
	for i in range(p1):
		o=i*5
		x=52200625L*u(p3,o)+614125*u(p3,o+1)+7225*u(p3,o+2)+85*u(p3,o+3)+u(p3,o+4)
		x,p=d(x,256)
		x,o=d(x,256)
		m,n=d(x,256)
		a(chr(m)+chr(n)+chr(o)+chr(p))
	if p2:
		p4+=(5-len(p4))*'!'
		x=52200625L*u(p4,0)+614125*u(p4,1)+7225*u(p4,2)+85*u(p4,3)+u(p4,4)
		x,p=d(x,256)
		x,o=d(x,256)
		m,n=d(x,256)
		a(chr(m))
		if p2>2:a(chr(n))
		if p2>3:a(chr(o))
	return ''.join(out)

def err(m):
	print '\033[91mError: %s\033[0m'%m
	sys.exit(1)

def unpack_wafdir(dir):
	f=open(sys.argv[0],'rb')
	c="corrupted waf (%d)"
	while 1:
		line=f.readline()
		if not line: err("waf-light must be run from a folder containing wafadmin")
		if line=='#==>\n':
			txt=f.readline()
			if not txt: err(c%1)
			if f.readline()!='#<==\n': err(c%2)
			break
	if not txt: err(c%3)
	try: txt=decode(txt[1:-1].replace('z', '!!!!!'))
	except: err(c%4)

	import shutil, tarfile
	try: shutil.rmtree(dir)
	except OSError: pass
	try: os.makedirs(j(dir, 'wafadmin', 'Tools'))
	except OSError: err("cannot unpack waf-local into %s Install waf system-wide or move waf into a writeable directory"%dir)

	os.chdir(dir)
	tmp='t.tbz2'
	t=open(tmp,'wb');t.write(txt);t.close()

	t=tarfile.open(tmp)
	for x in t: t.extract(x)
	t.close()

	os.unlink(tmp)
	os.chdir(cwd)

def test(dir):
	try: os.stat(j(dir,'wafadmin')); return os.path.abspath(dir)
	except OSError: pass

def find_lib():
	name=sys.argv[0]
	base=os.path.dirname(os.path.abspath(name))

	#devs use $WAFDIR
	w=test(os.environ.get('WAFDIR',''))
	if w: return w

	#waf-light
	if os.path.basename(name)=='waf-light':
		w=test(base)
		if w:return w
		err("waf-light in use, wafadmin not found -> export WAFDIR=/folder")

	dir="/lib/waf-%s-%s/" % (VERSION, REVISION)
	for i in [INSTALL,'/usr','/usr/local','/opt']:
		w=test(i+dir)
		if w:return w

	#waf-local
	if sys.platform=='win32': s='waf-%s-%s'
	else: s='.waf-%s-%s'
	dir=j(base,s%(VERSION,REVISION))
	w=test(dir)
	if w:return w

	#unpack
	unpack_wafdir(dir)
	return dir

wafdir=find_lib()
if "-vv" in sys.argv: print "wafdir is %s"%wafdir

w=j(wafdir,'wafadmin')
t=j(w,'Tools')
sys.path.extend([w,t])

import Params, Scripting
Params.g_tooldir=[t]
Params.g_cwd_launch=cwd

if Params.g_version!=VERSION:
	err('Version mismatch: waf %s <> wafadmin %s (wafdir %s)'%(VERSION,Params.g_version,wafdir))
Scripting.prepare()

