import Params

def build(bld):
	obj = bld.create_obj('cc', 'plugin')
	obj.target = 'pk_backend_apt'
	obj.source = 'pk-backend-apt.c'
	obj.uselib = 'APT'
	obj.uselib_local = 'libpackagekit'
	obj.includes = '../../src ../../libpackagekit'

	env = bld.env_of_name('default')
	if env['APT_SEARCH_PLAIN']:
		obj.source += ' pk-apt-search-plain.c'

def configure(conf):
	if not conf.find_program('apt-get'):
		return False

	# This check assumes the same python version that executes
	# waf will execute PackageKit.
	try:
		import apt_pkg
	except:
		Params.fatal('The "apt" backend needs "python-apt"')

	if not conf.check_library2('apt-pkg', uselib='APT'):
		return False
	
	if Params.g_options.apt_search:
		conf.env['APT_SEARCH_PLAIN'] = True

	return True

def set_options(opt):
	opt.add_option('--apt-search', type='string',
	               help='Apt search type to use - plain (plain)',
	               dest='apt_search', default=False)
