#!/usr/bin/python

#Marshall file
libselftest = bld.create_obj('gnome', 'objects')
libselftest.env.append_value('CCFLAGS', libselftest.env['shlib_CCFLAGS'])

libselftest.uselib = 'GLIB GOBJECT'

libselftest.source = """
	libselftest.c
"""

libselftest.includes = '.'
#libselftest.target   = 'libselftest'
libselftest.name     = 'libselftest'
