#!/usr/bin/python

#Marshall file
libpackagekit = bld.create_obj('gnome', 'shlib')
libpackagekit.add_marshal_file('pk-marshal.list', 'pk_marshal', '--header')
libpackagekit.add_marshal_file('pk-marshal.list', 'pk_marshal', '--body')
libpackagekit.uselib = 'GLIB GOBJECT'

libpackagekit.source='''
pk-debug.c
pk-debug.h
pk-connection.c
pk-connection.h
pk-network.h
pk-package-id.c
pk-package-id.h
pk-package-list.c
pk-package-list.h
pk-enum-list.c
pk-enum-list.h
pk-enum.h
pk-enum.c
pk-common.c
pk-common.h
pk-client.c
pk-client.h
pk-task-list.c
pk-task-list.h
pk-job-list.c
pk-job-list.h
pk-polkit-client.c
pk-polkit-client.h
'''
#pk-marshal.c
#pk-marshal.h

libpackagekit.includes      = '.'
libpackagekit.target        = 'libpackagekit'
libpackagekit.name          = 'libpackagekit'
