import Params

def build(bld):
	pass

def configure(conf):
	if not Params.g_options.default_backend:
		if conf.find_program('yum'):
			default_backend = 'yum'
		elif conf.check_library2('alpm', mandatory=0):
			default_backend = 'alpm'
		elif conf.find_program('apt-get'):
			default_backend = 'apt'
		elif conf.find_program('conary'):
			default_backend = 'conary'
		elif conf.find_program('box-repos'):
			default_backend = 'box'
		elif conf.find_program('smart'):
			default_backend = 'smart'
		elif conf.find_program('pisi'):
			default_backend = 'pisi'
		else:
			default_backend = 'dummy'
	else:
		default_backend = Params.g_options.default_backend

	if default_backend == 'box':
		if not conf.check_pkg('libbox', destvar='BOX'):
			Params.fatal('The "box" backend needs "libbox"')

	if default_backend == 'alpm':
		if not conf.check_header('alpm.h'):
			Params.fatal('The "alpm" backend needs "alpm.h"')

	if default_backend == 'apt':
		try:
			import apt_pkg
		except:
			Params.fatal('The "apt" backend needs "python-apt"')

		if not conf.check_library2('apt-pkg', uselib='APT'):
			Params.fatal('The "apt" backend needs "libapt-pkg-dev"')

def set_options(opt):
	opt.add_option('--default-backend', type='string', help="Default backend to use alpm,apt,box,conary,dummy,smart,yum,pisi", dest="default_backend")
