#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 Richard Hughes <richard@hughsie.com>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

bld.add_subdirs('dummy test')

#only contine compiling the correct backend
foo = 'the correct backend name'
if foo = 'yum':
	bld.add_subdirs('yum')
elif foo = 'alpm':
	bld.add_subdirs('alpm')
elif foo = 'apt':
	bld.add_subdirs('apt')
elif foo = 'conary':
	bld.add_subdirs('conary')
elif foo = 'box':
	bld.add_subdirs('box')
elif foo = 'smart':
	bld.add_subdirs('smart')
elif foo = 'pisi':
	bld.add_subdirs('pisi')

