import Params

def build(bld):
	env = bld.env_of_name('default')
	bld.add_subdirs(env['DEFAULT_BACKEND'])

def configure(conf):
	default_backend = None
	if Params.g_options.default_backend:
		if not conf.sub_config(Params.g_options.default_backend):
			Params.fatal('%s failed to configure' % Params.g_options.default_backend)
		default_backend = Params.g_options.default_backend

	if not default_backend:
		#Falls back to dummy if not backend was set
		for backend in ['yum', 'apt', 'alpm', 'conary', 'box', 'smart', 'pisi', 'dummy']:
			if conf.sub_config(backend):
				default_backend = backend
				break

	conf.env['DEFAULT_BACKEND'] = default_backend

def set_options(opt):
	opt.add_option('--default-backend', type='string', help="Default backend to use alpm,apt,box,conary,dummy,smart,yum,pisi", dest="default_backend")

	opt.sub_options('apt')
