#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 Richard Hughes <richard@hughsie.com>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

import misc

#set the default backend in the installed config file
obj=bld.create_obj('subst')
obj.source = 'PackageKit.conf.in'
obj.target = 'PackageKit.conf'
#TODO: need to get this from wscript
obj.dict = {'defaultbackend': 'default_backend'}
obj.fun = misc.subst_func
obj.install_var = 'PREFIX'
obj.install_subdir = 'etc/PackageKit'

