#!/bin/bash
# Copyright (C) 2007-2008 Richard Hughes <richard@hughsie.com>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

case "$1" in
	thaw|resume)
		# get PackageKit to invalidate its caches and get new updates
		dbus-send --system --dest=org.freedesktop.PackageKit \
			  --type=method_call \
			  /org/freedesktop/PackageKit \
			  org.freedesktop.PackageKit.StateHasChanged \
			  string:'resume'
		;;
	*)
		;;
esac

exit $?

