def build(bld):
	obj = bld.create_obj('cc', 'plugin')
	obj.target = 'pk_backend_dummy'
	obj.source = 'pk-backend-dummy.c'
	obj.uselib_local = 'libpackagekit'
	obj.includes = '../../src ../../libpackagekit'
	obj.install_var = 'LIBDIR'
	obj.install_subdir = 'packagekit-backend'

def configure(conf):
	return True

def set_options(opt):
	pass
