#!/bin/bash

. /usr/lib/pm-utils/functions

case "$1" in
	thaw|resume)
		# get PackageKit to invalidate its caches and get new updates
		dbus-send --system --dest=org.freedesktop.PackageKit \
			  --type=method_call --print-reply \
			  /org/freedesktop/PackageKit \
			  org.freedesktop.PackageKit.StateHasChanged
		;;
	*)
		;;
esac

exit $?

