#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 Richard Hughes <richard@hughsie.com>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

#only install if we are testing
if Params.g_options.tests:
	bld.add_subdirs('tests')

#set the servicedir in org.freedesktop.PackageKit.service and install
obj=bld.create_obj('subst')
obj.source = 'org.freedesktop.PackageKit.service.in'
obj.target = 'org.freedesktop.PackageKit.service'
obj.dict = {'servicedir': '/usr/sbin'}
obj.fun = misc.subst_func
obj.install_var = 'PREFIX'
obj.install_subdir = 'usr/share/dbus-1/system-services'

#TODO: install properly
install_files('var', 'run', 'PackageKit', 'job_count.dat')
install_files('var', 'lib', 'PackageKit', 'transactions.db')

