#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 Richard Hughes <richard@hughsie.com>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

bld.add_subdirs('tests')

#TODO: convert org.freedesktop.PackageKit.service.in to org.freedesktop.PackageKit.service
#after populating @servicedir@ to $(sbindir)

#TODO: install properly
install_files('$(localstatedir)', 'run', 'PackageKit', 'job_count.dat')
install_files('$(PK_DB_DIR)', 'PackageKit', 'transactions.db')

