[Backend]
Exec=portageBackend.py
Description=Portage
Author=Mounir Lamouri (volkmar) <mounir.lamouri@gmail.com>, Fabio Erculiani (lxnay) <lxnay@gentoo.org>, Mihai Morovan <hithack9@gmail.com>
# allowing sigkill as long as no one complains
AllowSigkill=true
