def build(bld):
	obj = bld.create_obj('cc', 'plugin')
	obj.target = 'pk_backend_box'
	obj.source = 'pk-backend-box.c'
	obj.uselib = 'BOX'
	obj.uselib_local = 'libpackagekit'
	obj.includes = '../../src ../../libpackagekit'
	obj.install_var = 'LIBDIR'
	obj.install_subdir = 'packagekit-backend'

def configure(conf):
	if not conf.find_program('box-repos'):
		return False
	if not conf.check_pkg('libbox', destvar='BOX'):
		return False
	return True

def set_options(opt):
	pass
