def build(bld):
	obj = bld.create_obj('cc', 'plugin')
	obj.target = 'pk_backend_alpm'
	obj.source = 'pk-backend-alpm.c'
	obj.uselib = 'ALPM'
	obj.uselib_local = 'libpackagekit'
	obj.includes = '../../src ../../libpackagekit'
	obj.install_var = 'LIBDIR'
	obj.install_subdir = 'packagekit-backend'

def configure(conf):
	if not conf.check_library2('alpm', uselib='ALPM', mandatory=0):
		return False
	if not conf.check_header('alpm.h'):
		return False

	return True

def set_options(opt):
	pass
