#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 Richard Hughes <richard@hughsie.com>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

import Utils

## FIXME: shouldn't it be: doc_subdir = os.path.join('doc', Utils.g_module.APPNAME) ?
doc_subdir = os.path.join(Utils.g_module.APPNAME, 'docs')

install_files('DATADIR', doc_subdir, 'pk-reference.html')
install_files('DATADIR', doc_subdir, 'pk-structure.png')
install_files('DATADIR', doc_subdir, 'docbook.css')

# xmlto html-nochunks -m config.xsl pk-reference.xml
cmd = bld.create_obj('command-output')
cmd.hidden_outputs = 'pk-reference.html'
cmd.command = 'xmlto'
cmd.command_is_external = True
cmd.cwd = cmd.input_dir('.') # xmlto is stupid, doesn't work from outside the xml source dir :(
cmd.argv = ['html-nochunks', '-m', cmd.input_file('config.xsl'),
            '--searchpath', cmd.input_dir('.'), '-o', cmd.output_dir('.'),
            cmd.input_file('pk-reference.xml')]
