#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 Richard Hughes <richard@hughsie.com>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

env = bld.env()

# Build the objects that are to be a part of both packagekitd and the testsuite
obj = bld.create_obj('gnome', 'objects')
obj.includes = '. ../libpackagekit ../libselftest ../libgbus'
obj.target = 'pkgkitd_common_source'
obj.uselib = 'DBUS_GLIB GMODULE SQLITE GTHREAD'
obj.add_marshal_file('pk-marshal.list', 'pk_marshal', '--header')
obj.add_marshal_file('pk-marshal.list', 'pk_marshal', '--body')
obj.source = """
	pk-backend.c
	pk-backend-python.c
	pk-conf.c
	pk-engine.c
	pk-inhibit.c
	pk-spawn.c
	pk-thread-list.c
	pk-time.c
	pk-transaction-db.c
	pk-transaction-id.c
	pk-transaction-list.c
""".split()

if env['SECURITY_TYPE_POLKIT']:
    obj.source += ['pk-security-polkit.c']

if env['SECURITY_TYPE_DUMMY']:
    obj.source += ['pk-security-dummy.c']

if env['SECURITY_TYPE_POLKIT']:
    obj.uselib += ' POLKIT_DBUS'

# Build packagekitd
#TODO: needs to be installed in /usr/sbin/packagekitd not /usr/bin/packagekitd
obj = bld.create_obj('gnome', 'program')
obj.target = 'packagekitd'
obj.source = 'pk-main.c'
obj.includes = '. ../libpackagekit ../libselftest ../libgbus'
obj.add_objects = 'pkgkitd_common_source'
obj.uselib = 'DBUS_GLIB GMODULE SQLITE GTHREAD'
obj.uselib_local = 'libpackagekit'
obj.add_dbus_file('pk-interface.xml', 'pk_engine', 'glib-server')
if env['SECURITY_TYPE_POLKIT']:
    obj.uselib += ' POLKIT_DBUS'
if env['HAVE_NETWORKMANAGER']:
	obj.uselib += ' NM_GLIB'

# Install backend headers to /usr/include/packagekit-backends/
install_files('PREFIX', 'include/packagekit-backends', """
		pk-backend.h
		pk-backend-python.h
""")

if env['HAVE_TESTS']:
	obj = bld.create_obj('cc', 'program')
	obj.source = 'pk-self-test.c'
	obj.add_objects = 'pkgkitd_common_source'
	obj.uselib = 'DBUS_GLIB GMODULE SQLITE GTHREAD GOBJECT POLKIT_DBUS'
	obj.uselib_local = 'libpackagekit'
	obj.target = 'test-packagekitd'
	obj.includes = '. ../libselftest ../libpackagekit'
	obj.install_var = 0
	if env['HAVE_NETWORKMANAGER']:
		obj.uselib += ' NM_GLIB'

#TODO: we really want a /src shutdown() method....
